safe: true
encoding: UTF-8
url: https://roundcube.net
enforce_ssl: roundcube.net
hostname: "https://roundcube.net"
permalink: news/:year/:month/:day/:title
exclude: [vendor]
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/news/page:num/"
environment: "production"
num_related_items: 5
libs: {
    fonts: {
        roboto: 'https://fonts.googleapis.com/css?family=Roboto&amp;display=swap',
        fontawesome: 'https://kit.fontawesome.com/4cdeb7a6e0.js'
    },
    less: {
        url: 'https://cdn.jsdelivr.net/npm/less@4.1.1/dist/less.min.js',
        sri: 'sha256-CYttzE5ypefNk7d3bCMASKNanIMq21aAUBEtlUfJ7C8='
    },
    css: '/styles/styles.min.css?v=2021092900',
    bootstrap: {
        css: {
            url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css',
            sri: 'sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC'
        },
        js: {
            url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js',
            sri: 'sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF'
        }
    }
}
